### ISSUE TITLE
Can't update sidecar list with less items

### ISSUE THREAD

**Issue by erdrix** [Orange-OpenSource/casskop#192]
# Bug Report

## What did you do

I create a CassandraCluster with the following `sidecarConfigs` (3 elements) : 

```yaml 
...
sidecarConfigs:
    - args: ["tail", "-F", "/var/log/cassandra/system.log"]
      image: registry.gitlab.si.francetelecom.fr/dfyarchicloud/dfyarchicloud-registry/alpine-tini
      imagePullPolicy: Always
      name: cassandra-log
      resources:
        limits:
          cpu: 50m
          memory: 50Mi
        requests:
          cpu: 10m
          memory: 10Mi
      volumeMounts:
        - mountPath: /var/log/cassandra
          name: cassandra-logs
    - args: ["tail", "-F", "/var/log/cassandra/gc.log.0.current"]
      image: registry.gitlab.si.francetelecom.fr/dfyarchicloud/dfyarchicloud-registry/alpine-tini
      imagePullPolicy: Always
      name: gc-log
      resources:
        limits:
          cpu: 50m
          memory: 50Mi
        requests:
          cpu: 10m
          memory: 10Mi
      volumeMounts:
        - mountPath: /var/log/cassandra
          name: gc-logs
    - args: ["tail", "-F", "/var/log/cassandra/gc.log.0.current"]
      image: registry.gitlab.si.francetelecom.fr/dfyarchicloud/dfyarchicloud-registry/alpine-tini
      imagePullPolicy: Always
      name: gc-log2
      resources:
        limits:
          cpu: 50m
          memory: 50Mi
        requests:
          cpu: 10m
          memory: 10Mi
...
```
And after I applied an update of `sidecarConfigs` with a lower number of elements : 

```yaml
...
  sidecarConfigs:
    - args: ["tail", "-F", "/var/log/cassandra/system.log"]
      image: registry.gitlab.si.francetelecom.fr/dfyarchicloud/dfyarchicloud-registry/alpine-tini
      imagePullPolicy: Always
      name: cassandra-log
      resources:
        limits:
          cpu: 50m
          memory: 50Mi
        requests:
          cpu: 10m
          memory: 10Mi
      volumeMounts:
        - mountPath: /var/log/cassandra
          name: cassandra-logs
    - args: ["tail", "-F", "/var/log/cassandra/gc.log.0.current"]
      image: registry.gitlab.si.francetelecom.fr/dfyarchicloud/dfyarchicloud-registry/alpine-tini
      imagePullPolicy: Always
      name: gc-log
      resources:
        limits:
          cpu: 50m
          memory: 50Mi
        requests:
          cpu: 10m
          memory: 10Mi
      volumeMounts:
        - mountPath: /var/log/cassandra
          name: gc-logs
...
```

## What did you expect to see?

A rolling upgrade of the statefulset

## What did you see instead? Under which circumstances?

The operator crashed with the following error : 

```log
time="2020-02-14T12:19:41Z" level=info msg="Starting the Cmd."
E0214 12:19:42.289415       1 runtime.go:78] Observed a panic: runtime.boundsError{x:3, y:3, signed:true, code:0x0} (runtime error: index out of range [3] with length 3)
goroutine 570 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x153f740, 0xc0004de4c0)
	casskop/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	casskop/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x153f740, 0xc0004de4c0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/Orange-OpenSource/casskop/pkg/controller/cassandracluster.statefulSetsAreEqual(0xc000c26468, 0xc000c25fc0, 0x6d)
	casskop/pkg/controller/cassandracluster/statefulset.go:142 +0x8e0
github.com/Orange-OpenSource/casskop/pkg/controller/cassandracluster.(*ReconcileCassandraCluster).CreateOrUpdateStatefulSet(0xc0006ae330, 0xc000180a00, 0xc000d22690, 0xc000503260, 0x9, 0x10, 0xc0002c3c00, 0xd)
	casskop/pkg/controller/cassandracluster/statefulset.go:256 +0xe33
github.com/Orange-OpenSource/casskop/pkg/controller/cassandracluster.(*ReconcileCassandraCluster).ensureCassandraStatefulSet(0xc0006ae330, 0xc0001db200, 0xc000d22690, 0xc0006fa280, 0x3, 0xc000503260, 0x9, 0x0, 0x0, 0x0, ...)
	casskop/pkg/controller/cassandracluster/deploy_cassandra.go:96 +0x262
github.com/Orange-OpenSource/casskop/pkg/controller/cassandracluster.(*ReconcileCassandraCluster).ReconcileRack(0xc0006ae330, 0xc0001db200, 0xc000d22690, 0x0, 0xe)
	casskop/pkg/controller/cassandracluster/reconcile.go:488 +0x5a9
github.com/Orange-OpenSource/casskop/pkg/controller/cassandracluster.(*ReconcileCassandraCluster).Reconcile(0xc0006ae330, 0xc0002c3c60, 0xe, 0xc0002c3c00, 0xd, 0xc000dc8c00, 0x0, 0x0, 0x0)
	casskop/pkg/controller/cassandracluster/cassandracluster_controller.go:156 +0x3b0
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0002d6540, 0x14ba8a0, 0xc000563c00, 0x0)
	casskop/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:256 +0x162
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0002d6540, 0x0)
	casskop/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232 +0xcb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc0002d6540)
	casskop/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000a9ac30)
	casskop/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000a9ac30, 0x3b9aca00, 0x0, 0x1, 0xc000aa5260)
	casskop/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc000a9ac30, 0x3b9aca00, 0xc000aa5260)
	casskop/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	casskop/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:193 +0x328
panic: runtime error: index out of range [3] with length 3 [recovered]
	panic: runtime error: index out of range [3] with length 3

goroutine 570 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	casskop/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105
panic(0x153f740, 0xc0004de4c0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/Orange-OpenSource/casskop/pkg/controller/cassandracluster.statefulSetsAreEqual(0xc000c26468, 0xc000c25fc0, 0x6d)
	casskop/pkg/controller/cassandracluster/statefulset.go:142 +0x8e0
github.com/Orange-OpenSource/casskop/pkg/controller/cassandracluster.(*ReconcileCassandraCluster).CreateOrUpdateStatefulSet(0xc0006ae330, 0xc000180a00, 0xc000d22690, 0xc000503260, 0x9, 0x10, 0xc0002c3c00, 0xd)
	casskop/pkg/controller/cassandracluster/statefulset.go:256 +0xe33
github.com/Orange-OpenSource/casskop/pkg/controller/cassandracluster.(*ReconcileCassandraCluster).ensureCassandraStatefulSet(0xc0006ae330, 0xc0001db200, 0xc000d22690, 0xc0006fa280, 0x3, 0xc000503260, 0x9, 0x0, 0x0, 0x0, ...)
	casskop/pkg/controller/cassandracluster/deploy_cassandra.go:96 +0x262
github.com/Orange-OpenSource/casskop/pkg/controller/cassandracluster.(*ReconcileCassandraCluster).ReconcileRack(0xc0006ae330, 0xc0001db200, 0xc000d22690, 0x0, 0xe)
	casskop/pkg/controller/cassandracluster/reconcile.go:488 +0x5a9
github.com/Orange-OpenSource/casskop/pkg/controller/cassandracluster.(*ReconcileCassandraCluster).Reconcile(0xc0006ae330, 0xc0002c3c60, 0xe, 0xc0002c3c00, 0xd, 0xc000dc8c00, 0x0, 0x0, 0x0)
	casskop/pkg/controller/cassandracluster/cassandracluster_controller.go:156 +0x3b0
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0002d6540, 0x14ba8a0, 0xc000563c00, 0x0)
	casskop/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:256 +0x162
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0002d6540, 0x0)
	casskop/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232 +0xcb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc0002d6540)
	casskop/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000a9ac30)
	casskop/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000a9ac30, 0x3b9aca00, 0x0, 0x1, 0xc000aa5260)
	casskop/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc000a9ac30, 0x3b9aca00, 0xc000aa5260)
	casskop/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	casskop/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:193 +0x328
```

## Environment 

- branch : master
- version : v0.5.1-release

## Possibile Solution

The bug comes from the statefulset check which compares container list : 
https://github.com/Orange-OpenSource/casskop/blob/master/pkg/controller/cassandracluster/statefulset.go#L142

If the current statefulset has more containers than the new one, the index will be out of range. 

To avoid this, we can simply add a comparison about length before.
