### ISSUE TITLE
Pods are not automatically balanced with hardAntiAffinity: false

### ISSUE THREAD

**Issue by sheerun** [Orange-OpenSource/casskop#210]
I've created cluster with following configuration:

```
apiVersion: "db.orange.com/v1alpha1"
kind: "CassandraCluster"
metadata:
  name: cassandra-cluster
  labels:
    cluster: k8s.kaas
spec:
  cassandraImage: cassandra:3.11.6
  bootstrapImage: orangeopensource/cassandra-bootstrap:0.1.4
  configMapName: cassandra-configmap-v1
  dataCapacity: "10Gi"
  dataStorageClass: ""
  imagepullpolicy: IfNotPresent  
  hardAntiAffinity: false
  deletePVC: true
  autoPilot: true
  gcStdout: true
  autoUpdateSeedList: true
  maxPodUnavailable: 1
  resources:         
    requests:
      cpu: '500m'
      memory: '512Mi'
    limits:
      cpu: '1000m'
      memory: '1024Mi'
  topology:
    dc:
      - name: dc1
        nodesPerRacks: 1
        rack:
          - name: rack1
          - name: rack2
          - name: rack3
```

on cluster with just one node. After all pods were Ready, I've scaled cluster size to 2 nodes, but all pods are still running on first node. I'd expect that they will autobalance into the second node? If it's not expected, can it be implemented as an option?
