### ISSUE TITLE
imageJolokiaSecret not used

### ISSUE THREAD

**Issue by eramirez51** [Orange-OpenSource/casskop#211]
As per the [Auth documentation](https://github.com/Orange-OpenSource/casskop/blob/master/documentation/description.md#authentication-and-authorizations), I have created a secret and created the cluster in the same namespace.

Cassandra enables Authentication, but uses the default username/password (cassandra/cassandra) instead of the values from `jolokia-auth`

Bootstrap logs says

```
...
Starting Cassandra on 10.11.1.18
Configuration used :
CASSANDRA_AUTHENTICATOR=PasswordAuthenticator
CASSANDRA_AUTHORIZER=CassandraAuthorizer
CASSANDRA_AUTH_JOLOKIA=false
CASSANDRA_AUTO_BOOTSTRAP=true
...
```

Below are my config. Please help. Thanks.

**Secret**
```
apiVersion: v1
kind: Secret
metadata:
  name: jolokia-auth
type: Opaque
data:
  password: cmVjb3JlY28=
  username: Y2Fzc2FuZHJh
```

**Cluster**
```
apiVersion: "db.orange.com/v1alpha1"
kind: "CassandraCluster"
metadata:
  name: cassandra-demo
  labels:
    cluster: k8s.kaas
spec:
  cassandraImage: cassandra:3.11
  bootstrapImage: orangeopensource/cassandra-bootstrap:0.1.4
  configMapName: cassandra-configmap-v1
  dataCapacity: "80Gi"
  dataStorageClass: "standard"
  imagepullpolicy: IfNotPresent  
  hardAntiAffinity: true           # Do we ensure only 1 cassandra on each node ?
  deletePVC: true
  autoPilot: false
  gcStdout: true
  autoUpdateSeedList: true
  maxPodUnavailable: 1
  runAsUser: 999
  imageJolokiaSecret:
    name: jolokia-auth
  topology:
    dc:
      - name: datacenter1
        nodesPerRacks: 3
        rack:
          - name: rack1
```

**configmap**
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-configmap-v1
data:
  pre_run.sh: |-
    echo "  ** this is pre_run.sh script executed before run.sh **"
    #Examples:
    grep max_hints_delivery_threads /etc/cassandra/cassandra.yaml
    sed -i 's/max_hints_delivery_threads: 2/max_hints_delivery_threads: 8/' /etc/cassandra/cassandra.yaml
    grep max_hints_delivery_threads /etc/cassandra/cassandra.yaml    
    echo "Change default Authenticator & Authorizer"
    sed -ri 's/(authenticator:).*/\1 PasswordAuthenticator/' /etc/cassandra/cassandra.yaml
    sed -ri 's/(authorizer:).*/\1 CassandraAuthorizer/' /etc/cassandra/cassandra.yaml

    #test "$(hostname)" == 'cassandra-demo-dc1-rack2-0' && echo "update param" && sed -i 's/windows_timer_interval: 1/windows_timer_interval: 2/' /etc/cassandra/cassandra.yaml
    #test "$(hostname)" == 'cassandra-demo-dc1-rack3-0' && echo "-Dcassandra.replace_address_first_boot=172.31.183.209" > /etc/cassandra/jvm.options
    #test "$(hostname)" == 'cassandra-demo-dc2-rack1-0' && echo "-Dcassandra.override_decommission=true" > /etc/cassandra/jvm.options    
    echo "  ** end of pre_run.sh script, continue with run.sh **"
  post_run.sh: |-
    echo "Check Configured seeds by bootstrap"
    grep "seeds:" /etc/cassandra/cassandra.yaml
```
