### ISSUE TITLE
Define additional env vars and/or volume mounts on bootstrap and cassandra containers

### ISSUE THREAD

**Issue by toffer** [Orange-OpenSource/casskop#271]
## Feature Request

**Is your feature request related to a problem? Please describe.**

By finalizing configuration in a bootstrap container, CassKop offers the user a great deal of power and flexibility to modify the Cassandra configuration before starting up the cassandra container. I really appreciate this feature.

However, some kinds of modifications would be much simpler if we had the ability to define additional environment variables, or mount additional configmaps or secrets as volumes, on the bootstrap and cassandra containers.

Some use cases:

1. **Set JMX auth**. While CassKop offers the ability to enable auth on Jolokia, there isn't a supported way to set auth on JMX. This is something that can easily be implemented in the `pre_run.sh` script, or in the bootstrap container in general. But, in order to do so, I'd like to be able to define environment variables for the JMX credentials, where the values come from k8s secrets.

2. **Register Cassandra pods**. We use a home-grown management system for our Cassandra clusters (the details of which are not important), and during startup, we would like each Cassandra pod to register themselves with our management service. This management service requires credentials, so ideally those would be available as env vars in the cassandra container. (Again, the values would come from k8s secrets.)

3. **Add TLS certificate**. Internode encryption requires a TLS certificate, and I'd like to be able to mount a k8s secret that contains the certificate as a volume in the Cassandra container.

**Describe the solution you'd like to see**

When you define sidecar containers in a CassandraCluster, you have the full power to set environment variables, add secrets, and mount secrets and configmaps as volumes. I'd love to see the same thing be possible with the bootstrap and cassandra containers.

Adding additional environment variables or volume mounts should be optional. No need to define them (or even think about them!) if you don't need this capability.

**Describe alternatives you've considered**

We've worked around this issue in various ways:

1. **Set JMX auth**. We've modified the startup script in our cassandra docker image to set JMX auth.
2. **Register Cassandra pods**. We use a sidecar container to do the registration.
3. **Add TLS certificate**. We're not sure the best way to work around this yet. Maybe a mutating webhook might work?

**Comment by cscetbon** [comment]
I think it's a fair request to allow users to add env vars and volumes to cassandra pods. Now the question is how to make it easy to specify in the crd. Maybe like https://github.com/Orange-OpenSource/casskop/blob/master/deploy/crds/db.orange.com_cassandraclusters_crd.yaml#L334 (I feel that this field should be called sidecarsConfig  instead of sidecarConfigs, wdyt ?), we could a field called containersConfig where the only acceptable name are [cassandra and bootstrap](https://github.com/Orange-OpenSource/casskop/blob/master/pkg/controller/cassandracluster/generator.go#L46-L47) This would be used to overwrite (probably by merging) the configuration of the default (init)Containers.

**Comment by toffer** [comment]
> Now the question is how to make it easy to specify in the crd.

Yes, that's a good question! Let me think about that for a bit.

**Comment by toffer** [comment]
I agree that any additional env var or volume mount should be merged and and should either overwrite the default configuration, or be added as an additional env var or volume mount.

All in all, I'm not sure how big of a change to the CRD you would be interested in. If you're willing to define new top-level fields, I'd probably favor separate, explicit naming like `bootstrapContainerConfig` and `cassandraContainerConfig`, rather than a list of `containerConfigs`. It might look like this:
```
spec:
  bootstrapContainerConfig:
    env:
    - name: ETCD_CONNECTION
      valueFrom:
        secretKeyRef:
          name: etcd-connection-secret
          key: etcd-connection
      - name: FOO
        value: bar
      - name: HOST_IP
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: spec.hostIP
    
    volumeMounts:
    - name: another-config
      mountPath: /another-configmap
    - name: another-secret
      mountPath: /another-secret
      readOnly: true
    
    volumes:
    - name: another-config
      configMap:
        defaultMode: 493
        name: another-configmap
    - name: another-secret
      secret:
        defaultMode: 420
        secretName: another-secret
      

  cassandraContainerConfig:
    env:
    - name: ETCD_CONNECTION
      valueFrom:
        secretKeyRef:
          name: etcd-connection-secret
          key: etcd-connection
      - name: FOO
        value: bar
      - name: HOST_IP
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: spec.hostIP
    
    volumeMounts:
    - name: another-config
      mountPath: /mnt/another-configmap
    - name: another-secret
      mountPath: /mnt/another-secret
      readOnly: true
    
    volumes:
    - name: another-config
      configMap:
        defaultMode: 493
        name: another-configmap
    - name: another-secret
      secret:
        defaultMode: 420
        secretName: another-secret
```
That way would give you maximum flexibility. You could target each container with different env vars and volumes, and mount the volumes on different paths in each pod

But, if you wanted to add this functionality to an already existing top-level field, then another idea would be to add additional fields to `pods`, so they would be defined alongside `annotations` and `tolerations`:
```
spec:
  pods:
    annotations:
      example.com/test: my.custom.annotation
    tolerations:
      - key: my_custom_taint
        operator: Exists
        effect: NoSchedule
    env:
    - name: ETCD_CONNECTION
      valueFrom:
        secretKeyRef:
          name: etcd-connection-secret
          key: etcd-connection
      - name: FOO
        value: bar
      - name: HOST_IP
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: spec.hostIP
    
    volumeMounts:
    - name: another-config
      mountPath: /another-configmap
    - name: another-secret
      mountPath: /another-secret
      readOnly: true
    
    volumes:
    - name: another-config
      configMap:
        defaultMode: 493
        name: another-configmap
    - name: another-secret
      secret:
        defaultMode: 420
        secretName: another-secret
```

The idea here is that these env vars, volumes and volume mounts would get added to all pods. (I would say "including sidecar pods", but that could be debated.) There's less flexibility with this approach, because you couldn't target individual pods. But, it may be a less significant change overall, both to the CRD and to the implementation.

I would be happy with either approach!
